


GET http://localhost:3001
###
GET http://localhost:3001/questions
###
PUT http://localhost:3001/questions/5dd08a8a580b33b6d58751e7

###
POST http://localhost:3001/questions
content-type: application/json

{
    "type": "Malware",
      "question": "Choose the correct malware definition-",
        "options": [
          "Malicious software",
          "Delicious software",
          "Maleficent software",
          "Suspicious software"
        ],
        "answer": "Malicious software"
}
